# Name of your blog (this will show up in the RSS feed)
name: Alan Pala[zzolo]
title: Alan Pala[zzolo]

# Short description (will also be used in the RSS feed)
description: Alan Palazzolo is an open source coder trying to make the world a little better with technology.

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: https://zzolo.org
url: https://zzolo.org

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
#auto: true

# Makes pretty permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Add syntax highlighting. Github uses rouge
highlighter: rouge

# As per Github
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _js
  - _images
  - LICENSE.code
  - package.json
  - README.md
  - webpack.config.js
  - config
